### ISSUE TITLE
ca-repo-migration-tool uses an older version of ca-service-base

### ISSUE THREAD

**Issue by agreedSkiing** [swedenconnect/ca-headless#4]
While checking the dependencies of headless-ca I noticed that it uses [ca-service-base 1.4.0](https://github.com/swedenconnect/ca-headless/blob/main/pom.xml#L38) while ca-repo-migration-tool (repo-migration) uses the [1.3.0 version](https://github.com/swedenconnect/ca-headless/blob/main/ca-repo-migration-tool/pom.xml#L41).

Should they be the same?

**Comment by Razumain** [comment]
Good catch. I will try to get a chance to fix this shortly.

**Comment by Razumain** [comment]
fixed in 1.3.1
